server:
  port: 8080
spring:
  application:
    name: customer
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: false # 不注册到 consul 中
  zipkin:  # zipkin 配置
#    base-url: http://localhost:8601 # 所有的数据提交到此服务
    sender:
      type: rabbit # 改用 rabbitMQ
  sleuth:
    sampler:
      probability: 1.0 # 定义抽样比率 100% 进行比例抽样，默认为 0.1
    messaging:
      rabbit:
        enabled: true
  rabbitmq: # rabbitmq 配置
    host: 192.168.134.130
    port: 5672
    username: admin
    password: rabbit
    virtual-host: /
    listener: # 配置重试策略
      direct:
        retry:
          enabled: true
      simple:
        retry:
          enabled: true
# feign 基本配置
feign:
  client:
    config:
      default:
        connectTimeout: 10000 # 连接超时时间，单位(毫秒)
        readTimeout: 10000 # 获取服务返回结果超时时间，单位(毫秒)
        loggerLevel: full # feign 的Http日志级别,full 为打印所有请求日志


