server:
  port: 80
spring:
  application:
    name: customer
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        register: false # 不注册到 consul 中
# feign 基本配置
feign:
  client:
    config:
      default:
        connectTimeout: 5000 # 连接超时时间，单位(毫秒)
        readTimeout: 5000 # 获取服务返回结果超时时间，单位(毫秒)
        loggerLevel: full # feign 的Http日志级别,full 为打印所有请求日志



