server:
  port: 8501
spring:
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        tags: version=1.0,author=code
        health-check-path: /info # 为健康检查的url,由consul定时调用一次判断服务是否可用
        health-check-interval: 5s # 检查间隔时间
        instance-id: ${spring.application.name}:prod # 注册的服务ID
        service-name: ${spring.application.name} # 注册的服务名称
        prefer-ip-address: true # 是否使用指定IP地址，默认为 false
        ip-address: 127.0.0.1 # 指定 IP 地址

  application:
    name: microcloud-consul-8501