server:
  port: 9101
turbine:
  appConfig: microcloud-consul,microcloud-consul-2222 # 要聚合的注册中心服务名
  clusterNameExpression: new String("default") # 默认为 default
  instanceUrlSuffix: manager/hystrix.stream # turbine 通过该地址获取到 hystrix 的对应数据,默认为 /actuator/hystrix.stream
  aggregator:
    cluster-config: 'default'

spring:
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${server.port}
        health-check-path: /manager/health # 检测是否健康
        register-health-check: true # 检测
        prefer-ip-address: true # 是否使用指定IP地址，默认为 false
        ip-address: 127.0.0.1 # 指定 IP 地址
        register: true # 注册

  application:
    name: turbine-9101
